import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertTriangle, BarChart3, CheckCircle2, DatabaseZap, Download, Gauge, Layers3, ListChecks, PhoneCall, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Target, TrendingUp, UsersRound, WalletCards, type LucideIcon } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Funnel, FunnelChart, LabelList, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';
import './unified.css';

type AtomicSource = 'onvest' | 'ontact' | 'powerbi';
type ApiSource = 'unified' | AtomicSource;
type Tab = 'command' | 'allMetrics' | 'journey' | 'sources' | 'vendors' | 'ontact' | 'media' | 'commercials' | 'powerbi' | 'explorer' | 'qa';
type Status = 'excellent' | 'good' | 'watch' | 'critical' | 'empty';
type FieldProfile = { source?: string; field: string; rawField?: string; group: string; role: string; type: string; numeric: boolean; pii: boolean; nonNull: number; total?: number; sampleValues: string[] };
type Row = Record<string, number | string>;
type Analytics = { fields: { numeric: string[]; text: string[] }; fieldCatalog: FieldProfile[]; columns: string[]; totals: Record<string, number>; derived: Record<string, number>; byDate: Row[]; byVendor: Row[]; byAgent: Row[]; byStatus: Row[]; records: Record<string, unknown>[]; recordsReturned: number; recordLimit: number };
type AnalyticsResult = { source: string; ok: boolean; configured: boolean; rows?: number; rawRows?: number; filteredRows?: number; excludedByDate?: number; undatedRowsExcluded?: number; upstreamCount?: number; truncated?: boolean; error?: string; queryDataEndpoint?: string; filters?: { from?: string; to?: string; strategy?: string; applied?: boolean }; analytics?: Analytics };
type Payload = { ok: boolean; mode: string; generatedAt: string; results: AnalyticsResult[] };
type Assumptions = { acceptedFee: number; ontactAgents: number; ontactOpexPerAgent: number; mtnActivation: number; blcActivation: number; mondoA: number; mondoB: number; mondoC: number; mondoD: number; mondoOther: number };
type PbiCanonical = { activations: number; captureComplete: number; nettApps: number; dateCreated: number };

type MetricRow = { source: string; metric: string; apiField: string; group: string; role: string; status: string; value: string; additive: string; usedIn: string; formula: string; samples: string };
type PerfRow = { name: string; score: number; spend: number; fetched: number; valid: number; delivered: number; accepted: number; qualified: number; sales: number; activations: number; cpl: number; cpaAccepted: number; validationRate: number; deliveryRate: number; acceptanceRate: number; salesRate: number; activationRate: number };

const moneyFmt = new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR', maximumFractionDigits: 0 });
const numFmt = new Intl.NumberFormat('en-ZA', { maximumFractionDigits: 0 });
const pctFmt = new Intl.NumberFormat('en-ZA', { style: 'percent', maximumFractionDigits: 1 });
const decFmt = new Intl.NumberFormat('en-ZA', { maximumFractionDigits: 1 });
const DEFAULT_ASSUMPTIONS: Assumptions = { acceptedFee: 35, ontactAgents: 0, ontactOpexPerAgent: 0, mtnActivation: 200, blcActivation: 900, mondoA: 75, mondoB: 17, mondoC: 10, mondoD: 10, mondoOther: 0 };
const NON_ADDITIVE = new Set(['uniqueid', 'lead_id', 'list_id', 'campaign_id', 'source_id', 'entry_list_id', 'start_epoch', 'end_epoch', 'gmt_offset_now', 'rank', 'model_id', 'dataset_id', 'report_id', 'phone_code']);
const moneyField = (key = '') => /amount|spend|revenue|profit|opex|cpl|cpa|fee/i.test(key);
const n = (v: unknown) => typeof v === 'number' && Number.isFinite(v) ? v : typeof v === 'string' ? Number(v.replace(/[^0-9.-]/g, '')) || 0 : 0;
const ratio = (a: unknown, b: unknown) => n(b) ? n(a) / n(b) : 0;
const fmt = (v: unknown, key = '') => moneyField(key) ? moneyFmt.format(n(v)) : numFmt.format(n(v));
const title = (v: string) => v.replace(/^.*\./, '').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()).replace(/Mtn/g, 'MTN').replace(/Blc/g, 'BLC').replace(/Rpc/g, 'RPC').replace(/Id/g, 'ID').replace(/Dnc/g, 'DNC').replace(/Fwa/g, 'FWA').replace(/Ftp/g, 'FTP');
const scoreAgainst = (value: number, target: number, lower = false) => Math.max(0, Math.min(100, target ? (lower ? target / Math.max(value, 0.00001) : value / target) * 100 : 0));
const avg = (xs: number[]) => xs.length ? xs.reduce((s, x) => s + x, 0) / xs.length : 0;

function emptyAnalytics(): Analytics { return { fields: { numeric: [], text: [] }, fieldCatalog: [], columns: [], totals: { records: 0 }, derived: {}, byDate: [], byVendor: [], byAgent: [], byStatus: [], records: [], recordsReturned: 0, recordLimit: 0 }; }
function isPayload(v: unknown): v is Payload { return !!v && typeof v === 'object' && typeof (v as Payload).generatedAt === 'string' && Array.isArray((v as Payload).results); }
function addRow(map: Map<string, Row>, keyName: string, row: Row) {
  const key = String(row[keyName] ?? 'Unknown');
  const bucket = map.get(key) ?? { [keyName]: key, records: 0 };
  for (const [k, v] of Object.entries(row)) if (k !== keyName) bucket[k] = n(bucket[k]) + n(v);
  map.set(key, bucket);
}
function mergeAnalytics(results: AnalyticsResult[]): Analytics {
  const available = results.filter(r => r.ok && r.analytics);
  if (!available.length) return emptyAnalytics();
  const totals: Record<string, number> = { records: 0 };
  const numeric = new Set<string>(); const text = new Set<string>(); const columns = new Set<string>(['__source']);
  const fieldCatalog: FieldProfile[] = []; const records: Record<string, unknown>[] = [];
  const byDate = new Map<string, Row>(); const byVendor = new Map<string, Row>(); const byAgent = new Map<string, Row>(); const byStatus = new Map<string, Row>();
  for (const result of available) {
    const a = result.analytics!;
    a.fields.numeric.forEach(f => numeric.add(f)); a.fields.text.forEach(f => text.add(f)); a.columns.forEach(c => columns.add(c));
    Object.entries(a.totals).forEach(([k, v]) => { totals[k] = (totals[k] ?? 0) + n(v); });
    fieldCatalog.push(...a.fieldCatalog.map(f => ({ ...f, source: result.source, rawField: f.field, field: `${result.source}.${f.field}` })));
    records.push(...a.records.map(r => ({ __source: result.source, ...r })));
    a.byDate.forEach(r => addRow(byDate, 'date', r)); a.byVendor.forEach(r => addRow(byVendor, 'vendor', r)); a.byAgent.forEach(r => addRow(byAgent, 'agent', r)); a.byStatus.forEach(r => addRow(byStatus, 'status', r));
  }
  return { fields: { numeric: [...numeric].sort(), text: [...text].sort() }, fieldCatalog, columns: [...columns], totals, derived: {}, byDate: [...byDate.values()].sort((a, b) => String(a.date).localeCompare(String(b.date))), byVendor: [...byVendor.values()].sort((a, b) => n(b.records) - n(a.records)), byAgent: [...byAgent.values()].sort((a, b) => n(b.records) - n(a.records)).slice(0, 80), byStatus: [...byStatus.values()].sort((a, b) => n(b.records) - n(a.records)), records: records.slice(0, 5000), recordsReturned: records.length, recordLimit: records.length };
}
function canonicalPowerBi(records: Record<string, unknown>[]): PbiCanonical {
  const sum = (query: string, field: string) => records.filter(r => r.__source === 'powerbi' && r.query === query).reduce((s, r) => s + n(r[field]), 0);
  return { activations: sum('activation_dates', 'count_activation'), captureComplete: sum('capture_complete_dates', 'count_capture_complete'), nettApps: sum('nett_app_dates', 'count_nett_app'), dateCreated: sum('date_created_on_capture_complete', 'count_date_created') };
}
function derived(t: Record<string, number>, pbi: PbiCanonical) {
  const mondoSales = n(t.Total_Leads_Sold_A) + n(t.Total_Leads_Sold_B) + n(t.Total_Leads_Sold_C) + n(t.Total_Leads_Sold_D) + n(t.Total_Leads_Sold_Other);
  const delivered = n(t.Total_Leads_Delivered_OnTact) + n(t.Total_Leads_Delivered_MTN) + n(t.Total_Leads_Delivered_Mondo) + n(t.DebtRescue_LeadDelivered) + n(t.Naga_FileDroppedOnFTP);
  const accepted = n(t.Accepted_Leads);
  const sales = n(t.MTN_Sales) + mondoSales;
  return { spend: n(t.Amount_Spent), impressions: n(t.Impressions), clicks: n(t.Clicks), lpv: n(t.Landing_Page_View), forms: n(t.Form_Completion), fetched: n(t.Fetched_Leads), valid: n(t.Total_Leads_WithValid_Phone_ID) || Math.min(n(t.Valid_IDNumber), n(t.Valid_Phone)), delivered, accepted, qualified: n(t.Qualified_Leads), sales, activations: n(t.MTN_Activated_Sales) + pbi.activations, mtnActivations: n(t.MTN_Activated_Sales), calls: n(t.__call_records) || n(t.records), talkSeconds: n(t.length_in_sec), dialed: n(t.MTN_Dialed_Leads), answered: n(t.MTN_Answered_Calls), rpc: n(t.MTN_Right_Party_Contact), cpl: ratio(t.Amount_Spent, n(t.Form_Completion) || n(t.Fetched_Leads)), cpaAccepted: ratio(t.Amount_Spent, accepted) };
}
function commercial(t: Record<string, number>, a: Assumptions, pbi: PbiCanonical) {
  const d = derived(t, pbi);
  const acceptedRevenue = d.accepted * a.acceptedFee;
  const mtnRevenue = n(t.MTN_Activated_Sales) * a.mtnActivation;
  const mondoRevenue = n(t.Total_Leads_Sold_A) * a.mondoA + n(t.Total_Leads_Sold_B) * a.mondoB + n(t.Total_Leads_Sold_C) * a.mondoC + n(t.Total_Leads_Sold_D) * a.mondoD + n(t.Total_Leads_Sold_Other) * a.mondoOther;
  const revenue = acceptedRevenue + mtnRevenue + mondoRevenue;
  const ontactOpex = a.ontactAgents * a.ontactOpexPerAgent;
  const grossProfit = revenue - d.spend - ontactOpex;
  return { acceptedRevenue, mtnRevenue, mondoRevenue, pbiOperationalRevenue: pbi.activations * a.blcActivation, revenue, ontactOpex, grossProfit, margin: ratio(grossProfit, revenue), roi: ratio(grossProfit, d.spend + ontactOpex), breakEvenAcceptedFee: d.accepted ? (d.spend + ontactOpex - mtnRevenue - mondoRevenue) / d.accepted : 0 };
}
function isAdditive(f: FieldProfile) {
  const raw = (f.rawField ?? f.field).split('.').pop() ?? f.field;
  const low = raw.toLowerCase();
  return f.numeric && !f.pii && f.role !== 'identifier' && f.role !== 'metadata' && f.role !== 'date/time' && !f.group.toLowerCase().includes('identifier') && !NON_ADDITIVE.has(raw) && !NON_ADDITIVE.has(low) && !low.endsWith('_id') && low !== 'id';
}
function sourceRows(records: Record<string, unknown>[]) {
  const map = new Map<string, Record<string, unknown>>();
  records.filter(r => r.__source === 'onvest' || r.offershop_source).forEach(r => {
    const key = String(r.offershop_source ?? r.source ?? r.__source ?? 'Unclassified');
    const b = map.get(key) ?? { source: key, records: 0 };
    b.records = n(b.records) + 1;
    Object.entries(r).forEach(([k, v]) => { if (!k.startsWith('__') && k !== 'offershop_source' && k !== 'date' && (typeof v === 'number' || (typeof v === 'string' && /^-?[\d,.]+$/.test(v.trim())))) b[k] = n(b[k]) + n(v); });
    map.set(key, b);
  });
  return [...map.values()].sort((a, b) => n(b.records) - n(a.records));
}
function perf(name: string, r: Record<string, unknown>, pbi: PbiCanonical): PerfRow {
  const spend = n(r.Amount_Spent), fetched = n(r.Fetched_Leads), valid = n(r.Total_Leads_WithValid_Phone_ID) || Math.min(n(r.Valid_IDNumber), n(r.Valid_Phone));
  const delivered = n(r.Total_Leads_Delivered_OnTact) + n(r.Total_Leads_Delivered_MTN) + n(r.Total_Leads_Delivered_Mondo) + n(r.DebtRescue_LeadDelivered) + n(r.Naga_FileDroppedOnFTP);
  const accepted = n(r.Accepted_Leads), qualified = n(r.Qualified_Leads), sales = n(r.MTN_Sales) + n(r.Total_Leads_Sold_A) + n(r.Total_Leads_Sold_B) + n(r.Total_Leads_Sold_C) + n(r.Total_Leads_Sold_D) + n(r.Total_Leads_Sold_Other);
  const activations = n(r.MTN_Activated_Sales) + (name === 'Power BI' ? pbi.activations : 0);
  const cpl = ratio(spend, n(r.Form_Completion) || fetched), cpaAccepted = ratio(spend, accepted);
  const validationRate = ratio(valid, fetched), deliveryRate = ratio(delivered, valid || fetched), acceptanceRate = ratio(accepted, fetched || delivered), salesRate = ratio(sales, accepted || fetched), activationRate = ratio(activations, sales || pbi.captureComplete);
  const score = avg([scoreAgainst(validationRate, .95), scoreAgainst(deliveryRate, .7), scoreAgainst(acceptanceRate, .45), scoreAgainst(salesRate, .18), scoreAgainst(activationRate, .08)].filter(Number.isFinite));
  return { name, score, spend, fetched, valid, delivered, accepted, qualified, sales, activations, cpl, cpaAccepted, validationRate, deliveryRate, acceptanceRate, salesRate, activationRate };
}
function metrics(a: Analytics, t: Record<string, number>, m: ReturnType<typeof commercial>, pbi: PbiCanonical): MetricRow[] {
  const api = a.fieldCatalog.map(f => {
    const raw = f.rawField ?? f.field, additive = isAdditive(f);
    const override = f.source === 'powerbi' && raw === 'count_activation' ? pbi.activations : f.source === 'powerbi' && raw === 'count_capture_complete' ? pbi.captureComplete : f.source === 'powerbi' && raw === 'count_nett_app' ? pbi.nettApps : undefined;
    const value = additive ? (override ?? n(f.total)) : f.nonNull;
    const status = f.pii ? 'protected' : f.nonNull === 0 ? 'missing' : additive && value === 0 ? 'zero' : 'live';
    return { source: f.source ?? 'unknown', metric: title(raw), apiField: raw, group: f.group, role: f.role, status, value: f.pii ? `Protected (${numFmt.format(f.nonNull)})` : additive ? fmt(value, raw) : `${numFmt.format(f.nonNull)} present`, additive: additive ? 'yes' : 'no', usedIn: additive ? 'Totals, charts, QA, exports' : 'Explorer, QA, row context', formula: additive ? `SUM(${raw}) after universal filtering${override !== undefined ? ' using canonical Power BI date query' : ''}` : 'Presence count after universal filtering', samples: f.pii ? '[protected]' : f.sampleValues.join(' | ') };
  });
  const d = derived(t, pbi);
  const dr = [ ['derived.cpl','CPL',d.cpl,'Commercial / cost','Spend ÷ forms or fetched leads'], ['derived.cpaAccepted','CPA Accepted',d.cpaAccepted,'Commercial / cost','Spend ÷ Accepted_Leads only'], ['derived.validRate','Valid Lead Rate',ratio(d.valid,d.fetched),'Lead quality','Valid leads ÷ fetched leads'], ['derived.deliveryRate','Delivery Rate',ratio(d.delivered,d.valid || d.fetched),'Routing quality','Delivered leads ÷ valid or fetched'], ['derived.salesRate','Sales Rate',ratio(d.sales,d.accepted || d.fetched),'Conversion / sales','Sales ÷ accepted or fetched'], ['commercial.revenue','Base Revenue',m.revenue,'Commercial model','Accepted + MTN + Mondo revenue'], ['commercial.grossProfit','Gross Profit',m.grossProfit,'Commercial model','Revenue - spend - opex'], ['commercial.breakEvenAcceptedFee','Break-even TP1 Fee',m.breakEvenAcceptedFee,'Commercial model','Required accepted fee for break-even'] ];
  return [...api, ...dr.map(([apiField, metric, value, group, formula]) => ({ source: 'derived', metric: String(metric), apiField: String(apiField), group: String(group), role: 'derived', status: 'derived', value: String(apiField).includes('Rate') ? pctFmt.format(n(value)) : fmt(value, String(apiField)), additive: 'no', usedIn: 'Command, QA, Commercials', formula: String(formula), samples: '' }))].sort((a, b) => a.source.localeCompare(b.source) || a.group.localeCompare(b.group) || a.metric.localeCompare(b.metric));
}
function journey(t: Record<string, number>, pbi: PbiCanonical) { const d = derived(t, pbi); const xs = [['Spend',d.spend,'Media investment'],['Impressions',d.impressions,'Paid reach proxy'],['Clicks',d.clicks,'Traffic action'],['Landing views',d.lpv,'Page arrival'],['Forms',d.forms,'Lead capture'],['Fetched',d.fetched,'Lead ingestion'],['Valid ID + phone',d.valid,'Data quality'],['Delivered',d.delivered,'Vendor / Ontact routing'],['Accepted',d.accepted,'TP1 commercial result'],['Qualified',d.qualified,'Sales-ready volume'],['Sales',d.sales,'Downstream conversion'],['Activations',d.activations,'Fulfilled result']].filter(x => n(x[1]) > 0); return xs.map((x, i) => ({ stage: String(x[0]), value: n(x[1]), rate: i ? ratio(x[1], xs[i-1][1]) : 1, lost: i ? Math.max(n(xs[i-1][1]) - n(x[1]), 0) : 0, note: String(x[2]) })); }
function qa(results: AnalyticsResult[], a: Analytics, all: MetricRow[], pbi: PbiCanonical) { return [ { check: 'API source health', status: results.length && results.every(r => r.ok) ? 'good' : 'critical', detail: results.map(r => `${r.source}: ${r.ok ? 'synced' : r.configured === false ? 'missing env vars' : r.error || 'sync failed'}`).join(' | ') || 'No API results.' }, { check: 'Exact source mapping', status: a.records.some(r => r.offershop_source) ? 'good' : 'watch', detail: 'Sources tab groups exact offershop_source. Vendor tab remains classified operational flow.' }, { check: 'Accepted vs delivered separation', status: 'good', detail: 'Accepted leads map only from Accepted_Leads. Delivered OnTact/MTN/Mondo remain delivery stages.' }, { check: 'Power BI double-count guard', status: 'good', detail: `Canonical activations use activation_dates only: ${numFmt.format(pbi.activations)}.` }, { check: 'All metrics coverage', status: all.length >= a.fieldCatalog.length ? 'good' : 'critical', detail: `${numFmt.format(all.length)} API and derived metrics visible.` }, { check: 'No demo data', status: 'good', detail: 'The app fetches /api/analytics only; no snapshot/demo fallback is loaded.' }, { check: 'Universal filter audit', status: results.some(r => r.filters?.applied || r.excludedByDate) ? 'good' : 'watch', detail: results.map(r => `${r.source}: raw ${numFmt.format(r.rawRows ?? r.upstreamCount ?? 0)} → filtered ${numFmt.format(r.filteredRows ?? r.rows ?? 0)} (${r.filters?.strategy ?? 'source-level'})`).join(' | ') } ] as { check: string; status: Status; detail: string }[]; }
function csv(name: string, rows: Record<string, unknown>[]) { const headers = Array.from(new Set(rows.flatMap(r => Object.keys(r)))); const data = [headers, ...rows.map(r => headers.map(h => r[h] ?? ''))].map(r => r.map(c => `"${String(c).replaceAll('"','""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([data], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }

function StatusBadge({ status }: { status: Status }) { return <span className={`status ${status}`}>{status}</span>; }
function Card({ title, value, sub, icon: Icon }: { title: string; value: string; sub: string; icon: LucideIcon }) { return <section className="card stat"><div className="stat-icon"><Icon size={18}/></div><div><p>{title}</p><strong>{value}</strong><span>{sub}</span></div></section>; }
function Panel({ title, sub, children, action }: { title: string; sub?: string; children: ReactNode; action?: ReactNode }) { return <section className="card panel"><div className="panel-head"><div><h2>{title}</h2>{sub && <p>{sub}</p>}</div>{action}</div>{children}</section>; }
function Table({ rows, columns }: { rows: Record<string, unknown>[]; columns?: string[] }) { const keys = columns ?? Array.from(new Set(rows.flatMap(r => Object.keys(r)))).slice(0, 80); if (!rows.length) return <div className="empty-state"><b>No rows returned</b><span>Sync the live API or adjust filters.</span></div>; return <div className="table-wrap"><table><thead><tr>{keys.map(k => <th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{keys.map(k => <td key={k}>{String(r[k] ?? '')}</td>)}</tr>)}</tbody></table></div>; }
function AssumptionInput({ label, value, onChange }: { label: string; value: number; onChange: (v: number) => void }) { return <label className="assumption"><span>{label}</span><input type="number" value={value} onChange={e => onChange(Number(e.target.value) || 0)}/></label>; }

function App() {
  const [payload, setPayload] = useState<Payload | null>(null); const [source, setSource] = useState<ApiSource>('unified'); const [tab, setTab] = useState<Tab>('command');
  const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [maxRows, setMaxRows] = useState('5000'); const [recordLimit, setRecordLimit] = useState('1000');
  const [search, setSearch] = useState(''); const [fieldSearch, setFieldSearch] = useState(''); const [metricGroup, setMetricGroup] = useState('all'); const [metricStatus, setMetricStatus] = useState('all'); const [metricSource, setMetricSource] = useState('all');
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [assumptions, setAssumptions] = useState(DEFAULT_ASSUMPTIONS);
  async function fetchOne(target: AtomicSource, mode: ApiSource): Promise<AnalyticsResult> { const rows = mode === 'unified' && target === 'ontact' ? '1000' : maxRows; const params = new URLSearchParams({ source: target, maxRows: rows, recordLimit: rows }); if (from) params.set('from', from); if (to) params.set('to', to); const response = await fetch(`/api/analytics?${params}`, { cache: 'no-store' }); const data = await response.json(); if (!isPayload(data)) throw new Error(`${target} returned an unexpected payload.`); return data.results[0] ?? { source: target, ok: false, configured: true, error: `${target} returned no result.` }; }
  async function load(next: ApiSource = source) { setLoading(true); setError(''); const targets: AtomicSource[] = next === 'unified' ? ['onvest','ontact','powerbi'] : [next]; const settled = await Promise.allSettled(targets.map(t => fetchOne(t, next))); const results = settled.map((r, i): AnalyticsResult => r.status === 'fulfilled' ? r.value : { source: targets[i], ok: false, configured: true, error: r.reason instanceof Error ? r.reason.message : String(r.reason) }); const live = { ok: results.every(r => r.ok), mode: next === 'unified' ? 'client-side-unified-live-api-sync' : 'single-source-live-api-sync', generatedAt: new Date().toISOString(), results }; setPayload(live); if (!live.ok) setError(results.filter(r => !r.ok).map(r => `${r.source}: ${r.configured === false ? 'missing Cloudflare env vars' : r.error || 'sync failed'}`).join(' | ')); setLoading(false); }
  useEffect(() => { void load('unified'); }, []);

  const results = payload?.results ?? []; const single = source === 'unified' ? undefined : results.find(r => r.source === source) ?? results[0]; const analytics = source === 'unified' ? mergeAnalytics(results) : single?.ok ? single.analytics ?? emptyAnalytics() : emptyAnalytics();
  const pbi = useMemo(() => canonicalPowerBi(analytics.records), [analytics.records]); const totals = analytics.totals; const d = derived(totals, pbi); const cm = commercial(totals, assumptions, pbi); const allMetrics = useMemo(() => metrics(analytics, totals, cm, pbi), [analytics, totals, cm, pbi]);
  const exactSources = sourceRows(analytics.records).map(r => perf(String(r.source), r, pbi)).filter(r => r.fetched || r.accepted || r.spend || r.sales).sort((a,b) => b.score - a.score);
  const vendors = analytics.byVendor.map(r => perf(String(r.vendor ?? 'Unknown'), r, pbi)).filter(r => r.fetched || r.accepted || r.sales || r.name === 'Power BI').sort((a,b) => b.score - a.score);
  const metricGroups = [...new Set(allMetrics.map(m => m.group))].sort(); const metricSources = [...new Set(allMetrics.map(m => m.source))].sort();
  const filteredMetrics = allMetrics.filter(m => (metricGroup === 'all' || m.group === metricGroup) && (metricStatus === 'all' || m.status === metricStatus) && (metricSource === 'all' || m.source === metricSource) && (!fieldSearch || `${m.source} ${m.apiField} ${m.metric} ${m.group} ${m.role}`.toLowerCase().includes(fieldSearch.toLowerCase())));
  const records = analytics.records.filter(r => !search || Object.values(r).some(v => String(v ?? '').toLowerCase().includes(search.toLowerCase()))).slice(0, 500);
  const mediaRows = analytics.byDate.map(r => ({ date: r.date, spend: n(r.Amount_Spent), impressions: n(r.Impressions), clicks: n(r.Clicks), forms: n(r.Form_Completion), cpl: ratio(r.Amount_Spent, n(r.Form_Completion) || n(r.Fetched_Leads)) }));
  const agentRows = analytics.byAgent.slice(0, 20).map(r => ({ agent: r.agent, records: r.records, calls: r.__call_records ?? r.records, talkSeconds: r.length_in_sec, avgSeconds: decFmt.format(ratio(r.length_in_sec, r.records)), sales: r.MTN_Sales ?? 0 }));
  const tabs: { id: Tab; label: string }[] = ['command','allMetrics','journey','sources','vendors','ontact','media','commercials','powerbi','explorer','qa'].map(id => ({ id: id as Tab, label: title(id === 'allMetrics' ? 'All Metrics' : id) }));

  return <main><aside className="sidebar"><div className="brand"><div className="brand-mark">CIQ</div><div><b>ConvertIQ</b><span>Performance Analytics</span></div></div><nav>{tabs.map(t => <button key={t.id} className={tab === t.id ? 'active' : ''} onClick={() => setTab(t.id)}>{t.label}</button>)}</nav><div className="sync-panel"><ShieldCheck size={18}/><b>API-only production mode</b><span>Exact source mapping, accepted/delivered separation and Power BI canonical totals are enforced.</span></div></aside><section className="workspace">
    <header className="hero"><div><p className="eyebrow">Live API sync · corrected mapping · universal filtering</p><h1>ConvertIQ Performance Command Center</h1><p>Every metric is mapped from live API data only. Source = exact offershop_source. Vendor = classified operational flow. Accepted leads = Accepted_Leads only.</p></div><button className="primary" onClick={() => load()} disabled={loading}><RefreshCw size={16} className={loading ? 'spin' : ''}/>{loading ? 'Syncing' : 'Sync dashboard'}</button></header>
    <section className="controls card"><SlidersHorizontal size={18}/><select value={source} onChange={e => { const next = e.target.value as ApiSource; setSource(next); void load(next); }}><option value="unified">Unified Dashboard</option><option value="onvest">Onvest API</option><option value="ontact">Ontact API</option><option value="powerbi">Power BI QueryData</option></select><input type="date" value={from} onChange={e => setFrom(e.target.value)}/><input type="date" value={to} onChange={e => setTo(e.target.value)}/><select value={maxRows} onChange={e => setMaxRows(e.target.value)}><option value="1000">1,000 rows</option><option value="5000">5,000 rows</option><option value="10000">10,000 rows</option><option value="15000">15,000 rows</option></select><select value={recordLimit} onChange={e => setRecordLimit(e.target.value)}><option value="250">Show 250</option><option value="1000">Show 1,000</option><option value="2500">Show 2,500</option><option value="5000">Show 5,000</option></select><button onClick={() => load()}>Apply</button><span>{payload ? `Last sync: ${new Date(payload.generatedAt).toLocaleString()}` : 'Waiting for API sync'}</span></section>
    {error && <section className="notice">{error}</section>}
    <section className="source-grid">{results.map(r => <section className="card source-card" key={r.source}><span className={r.ok ? 'pill ok' : 'pill warn'}>{r.ok ? 'API synced' : 'Attention'}</span><h3>{r.source.toUpperCase()}</h3><p>{numFmt.format(r.rows ?? 0)} rows · {numFmt.format(r.analytics?.fieldCatalog.length ?? 0)} parameters {r.truncated ? '· capped' : ''}</p></section>)}<section className="card source-card"><span className="pill ok">Coverage</span><h3>{numFmt.format(allMetrics.length)}</h3><p>API + derived metrics visible.</p></section></section>

    {tab === 'command' && <><section className="kpi-grid"><Card title="Revenue" value={moneyFmt.format(cm.revenue)} sub="TP1 + MTN + Mondo" icon={WalletCards}/><Card title="Gross Profit" value={moneyFmt.format(cm.grossProfit)} sub={`${pctFmt.format(cm.margin)} margin`} icon={TrendingUp}/><Card title="Spend" value={moneyFmt.format(d.spend)} sub="Media cost" icon={DatabaseZap}/><Card title="Fetched Leads" value={numFmt.format(d.fetched)} sub={`${pctFmt.format(ratio(d.valid,d.fetched))} valid`} icon={UsersRound}/><Card title="Accepted Leads" value={numFmt.format(d.accepted)} sub="Accepted_Leads only" icon={Gauge}/><Card title="Power BI Activations" value={numFmt.format(pbi.activations)} sub="activation_dates canonical" icon={ListChecks}/></section><section className="grid two"><Panel title="Performance trend"><ResponsiveContainer width="100%" height={330}><AreaChart data={analytics.byDate}><CartesianGrid vertical={false}/><XAxis dataKey="date"/><YAxis/><Tooltip/><Area dataKey="Amount_Spent" name="Spend"/><Area dataKey="Accepted_Leads" name="Accepted"/><Area dataKey="MTN_Sales" name="MTN Sales"/><Area dataKey="count_activation" name="Activations"/></AreaChart></ResponsiveContainer></Panel><Panel title="QA recommendations"><div className="diagnostic-list">{qa(results, analytics, allMetrics, pbi).map(x => <article className={`diagnostic ${x.status}`} key={x.check}><AlertTriangle size={16}/><div><b>{x.check}</b><span>{x.detail}</span></div><StatusBadge status={x.status}/></article>)}</div></Panel></section></>}
    {tab === 'allMetrics' && <><section className="metric-hero card"><div><span>All metrics cockpit</span><h2>{numFmt.format(allMetrics.length)} metrics visible</h2><p>Includes live fields, corrected derived metrics, protected PII markers and Power BI canonical totals.</p></div><div className="metric-hero-grid"><article><span>API fields</span><strong>{numFmt.format(allMetrics.filter(m => m.source !== 'derived').length)}</strong></article><article><span>Derived</span><strong>{numFmt.format(allMetrics.filter(m => m.source === 'derived').length)}</strong></article><article><span>Live</span><strong>{numFmt.format(allMetrics.filter(m => m.status === 'live').length)}</strong></article><article><span>Protected</span><strong>{numFmt.format(allMetrics.filter(m => m.status === 'protected').length)}</strong></article></div></section><Panel title="Metric controls" action={<button className="secondary" onClick={() => csv('convertiq-all-metrics.csv', filteredMetrics)}><Download size={14}/>Export</button>}><div className="metric-controls"><div className="inline-tools"><Search size={16}/><input placeholder="Search metric" value={fieldSearch} onChange={e => setFieldSearch(e.target.value)}/></div><select value={metricSource} onChange={e => setMetricSource(e.target.value)}><option value="all">All sources</option>{metricSources.map(s => <option key={s}>{s}</option>)}</select><select value={metricGroup} onChange={e => setMetricGroup(e.target.value)}><option value="all">All groups</option>{metricGroups.map(g => <option key={g}>{g}</option>)}</select><select value={metricStatus} onChange={e => setMetricStatus(e.target.value)}><option value="all">All statuses</option><option value="live">Live</option><option value="zero">Zero</option><option value="protected">Protected</option><option value="derived">Derived</option><option value="missing">Missing</option></select></div></Panel><Panel title="Complete metric audit table"><Table rows={filteredMetrics}/></Panel></>}
    {tab === 'journey' && <section className="grid two"><Panel title="Full-funnel waterfall" sub="Delivered and accepted are separate mapped stages"><ResponsiveContainer width="100%" height={460}><FunnelChart><Tooltip/><Funnel dataKey="value" data={journey(totals, pbi)}><LabelList position="right" fill="#17202a" stroke="none" dataKey="stage"/></Funnel></FunnelChart></ResponsiveContainer></Panel><Panel title="Leakage audit"><Table rows={journey(totals, pbi).map(r => ({ stage: r.stage, value: numFmt.format(r.value), stepRate: pctFmt.format(r.rate), lost: numFmt.format(r.lost), note: r.note }))}/></Panel></section>}
    {tab === 'sources' && <><section className="grid two"><Panel title="Exact source score ranking" sub="Grouped by offershop_source, not vendor"><ResponsiveContainer width="100%" height={360}><BarChart data={exactSources.slice(0,14)}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="score"/></BarChart></ResponsiveContainer></Panel><Panel title="Source economics"><ResponsiveContainer width="100%" height={360}><BarChart data={exactSources.slice(0,14)}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="spend" name="Spend"/><Bar dataKey="accepted" name="Accepted"/></BarChart></ResponsiveContainer></Panel></section><Panel title="Source performance matrix" action={<button className="secondary" onClick={() => csv('convertiq-source-performance.csv', exactSources)}><Download size={14}/>Export</button>}><Table rows={exactSources.map(r => ({ source: r.name, score: decFmt.format(r.score), spend: moneyFmt.format(r.spend), fetched: numFmt.format(r.fetched), validRate: pctFmt.format(r.validationRate), deliveryRate: pctFmt.format(r.deliveryRate), accepted: numFmt.format(r.accepted), cpaAccepted: r.cpaAccepted ? moneyFmt.format(r.cpaAccepted) : '-', sales: numFmt.format(r.sales) }))}/></Panel></>}
    {tab === 'vendors' && <section className="grid two"><Panel title="Vendor delivery matrix"><Table rows={[{ vendor:'BLC / OnTact', vetted:totals.Total_Leads_Passed_BLC_Vetting ?? 0, delivered:totals.Total_Leads_Delivered_OnTact ?? 0 },{ vendor:'MTN', leads:totals.Total_Leads_Is_MTN_Lead ?? 0, delivered:totals.Total_Leads_Delivered_MTN ?? 0, dialed:totals.MTN_Dialed_Leads ?? 0, answered:totals.MTN_Answered_Calls ?? 0, sales:totals.MTN_Sales ?? 0, activated:totals.MTN_Activated_Sales ?? 0 },{ vendor:'Mondo', gradePassed:totals.Total_Mondo_Grade_Passed_Lead ?? 0, delivered:totals.Total_Leads_Delivered_Mondo ?? 0, soldA:totals.Total_Leads_Sold_A ?? 0, soldB:totals.Total_Leads_Sold_B ?? 0, soldC:totals.Total_Leads_Sold_C ?? 0, soldD:totals.Total_Leads_Sold_D ?? 0 },{ vendor:'Naga', processed:totals.Naga_Processed ?? 0, ftpDropped:totals.Naga_FileDroppedOnFTP ?? 0 },{ vendor:'Debt Rescue', processed:totals.DebtRescua_Processed ?? 0, delivered:totals.DebtRescue_LeadDelivered ?? 0 }]}/></Panel><Panel title="Vendor composition"><ResponsiveContainer width="100%" height={360}><BarChart data={vendors.slice(0,12)}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="fetched"/><Bar dataKey="accepted"/><Bar dataKey="sales"/></BarChart></ResponsiveContainer></Panel></section>}
    {tab === 'ontact' && <><section className="kpi-grid compact"><Card title="Call Records" value={numFmt.format(d.calls)} sub="Ontact rows / records" icon={PhoneCall}/><Card title="Talk Time" value={`${decFmt.format(d.talkSeconds/3600)}h`} sub="length_in_sec" icon={Activity}/><Card title="Answer Rate" value={pctFmt.format(ratio(d.answered,d.dialed))} sub={`${numFmt.format(d.answered)} answered`} icon={CheckCircle2}/><Card title="RPC Rate" value={pctFmt.format(ratio(d.rpc,d.answered))} sub={`${numFmt.format(d.rpc)} RPC`} icon={Target}/></section><Panel title="Agent productivity"><Table rows={agentRows}/></Panel></>}
    {tab === 'media' && <><section className="kpi-grid compact"><Card title="Impressions" value={numFmt.format(d.impressions)} sub="Media delivery" icon={Layers3}/><Card title="Clicks" value={numFmt.format(d.clicks)} sub={`${pctFmt.format(ratio(d.clicks,d.impressions))} CTR`} icon={BarChart3}/><Card title="Landing Views" value={numFmt.format(d.lpv)} sub="LPV" icon={BarChart3}/><Card title="Forms" value={numFmt.format(d.forms)} sub={`${moneyFmt.format(d.cpl)} CPL`} icon={ListChecks}/></section><Panel title="Media efficiency by day"><ResponsiveContainer width="100%" height={380}><LineChart data={mediaRows}><CartesianGrid vertical={false}/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line dataKey="spend"/><Line dataKey="clicks"/><Line dataKey="forms"/><Line dataKey="cpl"/></LineChart></ResponsiveContainer></Panel></>}
    {tab === 'commercials' && <><section className="assumptions card"><AssumptionInput label="TP1 accepted fee" value={assumptions.acceptedFee} onChange={v => setAssumptions({...assumptions,acceptedFee:v})}/><AssumptionInput label="OnTact agents" value={assumptions.ontactAgents} onChange={v => setAssumptions({...assumptions,ontactAgents:v})}/><AssumptionInput label="Opex / agent" value={assumptions.ontactOpexPerAgent} onChange={v => setAssumptions({...assumptions,ontactOpexPerAgent:v})}/><AssumptionInput label="MTN payout" value={assumptions.mtnActivation} onChange={v => setAssumptions({...assumptions,mtnActivation:v})}/><AssumptionInput label="BLC reference" value={assumptions.blcActivation} onChange={v => setAssumptions({...assumptions,blcActivation:v})}/></section><section className="kpi-grid"><Card title="Base Revenue" value={moneyFmt.format(cm.revenue)} sub="TP1 + MTN + Mondo" icon={WalletCards}/><Card title="Accepted Revenue" value={moneyFmt.format(cm.acceptedRevenue)} sub={`${numFmt.format(d.accepted)} accepted`} icon={Target}/><Card title="Mondo Revenue" value={moneyFmt.format(cm.mondoRevenue)} sub="A/B/C/D" icon={BarChart3}/><Card title="MTN Revenue" value={moneyFmt.format(cm.mtnRevenue)} sub={`${numFmt.format(d.mtnActivations)} activations`} icon={CheckCircle2}/><Card title="OnTact Opex" value={moneyFmt.format(cm.ontactOpex)} sub="Manual assumption" icon={PhoneCall}/><Card title="Break-even TP1" value={moneyFmt.format(cm.breakEvenAcceptedFee)} sub="Accepted fee needed" icon={Gauge}/></section></>}
    {tab === 'powerbi' && <section className="grid two"><Panel title="Power BI canonical summary" sub="Date-level queries prevent duplicate aggregate totals"><Table rows={[{ metric:'Canonical activations', value:numFmt.format(pbi.activations) },{ metric:'Canonical capture complete', value:numFmt.format(pbi.captureComplete) },{ metric:'Canonical nett apps', value:numFmt.format(pbi.nettApps) },{ metric:'Endpoint', value:results.find(r => r.source === 'powerbi')?.queryDataEndpoint ?? 'Unavailable' }]}/></Panel><Panel title="Power BI rows"><Table rows={analytics.records.filter(r => r.__source === 'powerbi').slice(0,200)}/></Panel></section>}
    {tab === 'explorer' && <><Panel title="Redacted row explorer" action={<div className="inline-tools"><Search size={16}/><input placeholder="Search rows" value={search} onChange={e => setSearch(e.target.value)}/><button className="secondary" onClick={() => csv('convertiq-redacted-rows.csv', records)}><Download size={14}/>Export</button></div>}><Table rows={records} columns={analytics.columns}/></Panel></>}
    {tab === 'qa' && <section className="grid two"><Panel title="QA checks"><div className="diagnostic-list">{qa(results, analytics, allMetrics, pbi).map(x => <article className={`diagnostic ${x.status}`} key={x.check}><ShieldCheck size={16}/><div><b>{x.check}</b><span>{x.detail}</span></div><StatusBadge status={x.status}/></article>)}</div></Panel><Panel title="Universal filter audit"><Table rows={results.map(r => ({ source:r.source, status:r.ok?'synced':'attention', rawRows:r.rawRows ?? r.upstreamCount ?? 0, filteredRows:r.filteredRows ?? r.rows ?? 0, excludedByDate:r.excludedByDate ?? 0, undatedExcluded:r.undatedRowsExcluded ?? 0, from:r.filters?.from ?? '', to:r.filters?.to ?? '', strategy:r.filters?.strategy ?? 'source-level' }))}/></Panel></section>}
  </section></main>;
}

createRoot(document.getElementById('root')!).render(<App />);
